easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            label: "Produits"
            list:
                fields:
                    -   'name'
                    - { property: 'imageName', type: 'image', base_path: '%app.path.product_images%' }
            show:
                fields:
                    -   'name'
                    - { property: 'imageName', type: 'image', base_path: '%app.path.product_images%' }
            form:
                fields:
                    - 'name'
                    - 'description'
                    - 'price'
                    - 'unit'
                    - 'step'
                    - 'stock'
                    - 'importance'
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'categories', type_options: { by_reference: false } }
        Category:
            class: App\Entity\Category
            label: 'Catégories'
            form:
                fields:
                    - 'category'
                    - 'description'
                    - { property: 'products', type: 'entity', type_options: { class: 'App\Entity\Product', multiple: true } }
                    - 'type'
        Type: 
            class: App\Entity\Type
            label: "Types de produits"
        Creation:
            class: App\Entity\Creation
            label: "Créations personnelles"
            form: 
                fields:
                    - 'title'
                    - 'description'
                    - 'date'
                    - { property: 'imageFile', type: 'vich_image' }
            list:
                fields:
                    -   'title'
                    - { property: 'imageName', type: 'image', base_path: '%app.path.creation_images%' }
            show:
                fields:
                    -   'title'
                    - { property: 'imageName', type: 'image', base_path: '%app.path.creation_images%' }
        EcommerceConfig:
            class: App\Entity\EcommerceConfig
            label: "Configuration Ecommerce"
            form:
                fields:
                    - 'tva'
        Commande:
            class: App\Entity\Commande
            label: 'Commandes'
            list:
                actions: ["show", "-edit", "-delete"]
        Customer:
            class: App\Entity\Customer
            label: 'Clients'
        CommandeBasket:
            class: App\Entity\CommandeBasket
            label: 'Produits achetés'
