swiftmailer:
    #url: '%env(MAILER_URL)%'
    transport: gmail
    encryption: tls
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASS)%'
    host: smtp.gmail.com
    port: 587
    auth-mode: login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
