swiftmailer:
    transport: smtp
    #spool: { type: file, path: test }
    encryption: null
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASS)%'
    host: 127.0.0.1
    port: 1025
    #auth-mode: null
    
