# debug:router
  # get_products                 GET      ANY      ANY    /api/products
  # get_product                  GET      ANY      ANY    /api/products/{id}
  # post_products                POST     ANY      ANY    /api/products
  # remove_product               DELETE   ANY      ANY    /api/products/{id}
  # update_product               PUT      ANY      ANY    /api/products/{id}
  # patch_product                PATCH    ANY      ANY    /api/products/{id}
  # get_productsby_category      GET      ANY      ANY    /api/categories/{id}/products
  # get_categories               GET      ANY      ANY    /api/categories
  # get_category                 GET      ANY      ANY    /api/categories/{id}
  # post_categories              POST     ANY      ANY    /api/categories
  # remove_category              DELETE   ANY      ANY    /api/categories/{id}
  # update_category              PUT      ANY      ANY    /api/categories/{id}
  # patch_category               PATCH    ANY      ANY    /api/categories/{id}   => Ici possible de modifier le "type": id
  # add_product_to_category      POST     ANY      ANY    /api/categories/{catid}/products/{prodid}/add
  # remove_product_to_category   POST     ANY      ANY    /api/categories/{catid}/products/{prodid}/remove
  # get_types                    GET      ANY      ANY    /api/types
  # get_type                     GET      ANY      ANY    /api/types/{id}
  # post_type                    POST     ANY      ANY    /api/types
  # remove_type                  DELETE   ANY      ANY    /api/types/{id}
  # update_type                  PUT      ANY      ANY    /api/types/{id}
  # patch_type                   PATCH    ANY      ANY    /api/types/{id}




admin_login_check:
    path: /apiadmin/login_check

api:
    resource: "@AppBundle/Controller/API/"
    type: rest
    prefix: /api

# products:
#     type:     rest
#     resource: AppBundle\Controller\ProductController
#     prefix: /api

# categories:
#     type:     rest
#     resource: AppBundle\Controller\CategoryController
#     prefix: /api

# types:
#     type:     rest
#     resource: AppBundle\Controller\TypeController
#     prefix: /api

commande:
    type:     rest
    resource: AppBundle\Controller\Admin\CommandeController
    prefix: /apiadmin


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

